In [5]:
import pandas as pd

data = pd.read_csv("/Users/macbookpro/platform/Backend/data/historical_data_2025/historical_data_2025Q1/historical_data_2025Q1.txt", sep="|")
data_t = pd.read_csv("/Users/macbookpro/platform/Backend/data/historical_data_2025/historical_data_2025Q1/historical_data_2025Q1.txt", sep="|")

In [4]:
data.head()

,786,202503,N,205502,41180,000,1,P,57,30,...,02,Other sellers,Other servicers,Unnamed: 25,Unnamed: 26,9,Unnamed: 28,2,N.3,7
0,812,202503,N,205502,47260.0,0,1,P,43,35,...,2,Other sellers,Other servicers,NaN,NaN,9,NaN,2,N,7
1,750,202503,Y,205502,NaN,25,1,P,90,35,...,1,Other sellers,NATIONSTAR MORTGAGE LLC DBA MR. COOPER,NaN,NaN,9,NaN,2,N,N
2,724,202503,Y,205502,NaN,0,1,P,54,46,...,2,Other sellers,Other servicers,NaN,NaN,9,NaN,2,N,7
3,578,202503,N,205502,23060.0,0,1,P,80,48,...,2,Other sellers,Other servicers,NaN,NaN,9,NaN,2,N,7
4,703,202503,N,205502,NaN,0,1,P,74,34,...,1,Other sellers,PHH ASSET SERVICES LLC,NaN,NaN,9,NaN,2,N,7

In [6]:
data_t.head()

,786,202503,N,205502,41180,000,1,P,57,30,...,02,Other sellers,Other servicers,Unnamed: 25,Unnamed: 26,9,Unnamed: 28,2,N.3,7
0,812,202503,N,205502,47260.0,0,1,P,43,35,...,2,Other sellers,Other servicers,NaN,NaN,9,NaN,2,N,7
1,750,202503,Y,205502,NaN,25,1,P,90,35,...,1,Other sellers,NATIONSTAR MORTGAGE LLC DBA MR. COOPER,NaN,NaN,9,NaN,2,N,N
2,724,202503,Y,205502,NaN,0,1,P,54,46,...,2,Other sellers,Other servicers,NaN,NaN,9,NaN,2,N,7
3,578,202503,N,205502,23060.0,0,1,P,80,48,...,2,Other sellers,Other servicers,NaN,NaN,9,NaN,2,N,7
4,703,202503,N,205502,NaN,0,1,P,74,34,...,1,Other sellers,PHH ASSET SERVICES LLC,NaN,NaN,9,NaN,2,N,7

# Restauration des Hea